intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

import impl_libs += build2%lib{build2} # Implied interface dependency.

lib{build2-snapshot}: {hxx ixx txx cxx}{** -version} \
                      {hxx            }{    version} $impl_libs $intf_libs

hxx{version}: in{version} $src_root/manifest

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

obja{*}: cxx.poptions += -DLIBBUILD2_SNAPSHOT_STATIC_BUILD
objs{*}: cxx.poptions += -DLIBBUILD2_SNAPSHOT_SHARED_BUILD

# Export options.
#
lib{build2-snapshot}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

liba{build2-snapshot}: cxx.export.poptions += -DLIBBUILD2_SNAPSHOT_STATIC
libs{build2-snapshot}: cxx.export.poptions += -DLIBBUILD2_SNAPSHOT_SHARED

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{build2-snapshot}: bin.lib.version = "-$version.project_id"
else
  lib{build2-snapshot}: bin.lib.version = "-$version.major.$version.minor"

# Embed the build system core version as our load suffix.
#
libs{build2-snapshot}: bin.lib.load_suffix = "-$build.version.interface"

# Install into the libbuild2/snapshot/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/libbuild2/snapshot/
  install.subdirs = true
}
